# Get user by Id
GET http://localhost:9090/user-management/users/2

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Wed, 18 Jun 2025 17:08:46 +0530
content-encoding: gzip
content-length: 119
###
# Get all the users
GET http://localhost:9090/user-management/users

HTTP/1.1 200  - OK
content-type: application/json
connection: close
server: ballerina
date: Wed, 18 Jun 2025 17:11:27 +0530
content-encoding: gzip
content-length: 151
###
# Search user by name
GET http://localhost:9090/user-management/users/search?name=sample"

HTTP/1.1 400  - Bad Request
content-type: application/json
connection: close
server: ballerina
date: Wed, 18 Jun 2025 14:06:46 +0530
content-encoding: gzip
content-length: 193
###
# Creat a user
POST http://localhost:9090/user-management/users
content-type: application/json

{
    "firstName": "User",
	"lastName": "One",
	"mobileNumber": "0771111111",
	"email": "user-one@user-management"
}

HTTP/1.1 201  - Created
content-type: application/json
connection: close
server: ballerina
date: Wed, 18 Jun 2025 15:13:02 +0530
content-encoding: gzip
content-length: 27
###
# Update a user
PUT http://localhost:9090/user-management/users
content-type: application/json

{
	"id": 1,
    "firstName": "User",
	"lastName": "Edited",
	"mobileNumber": "0771111111",
	"email": "user-one-edited@tyrnt.co"
}

HTTP/1.1 200  - OK
content-type: text/plain
connection: close
server: ballerina
date: Wed, 18 Jun 2025 16:50:44 +0530
content-encoding: gzip
content-length: 46
###
# Delete user by Id
DELETE http://localhost:9090/user-management/users/2

HTTP/1.1 204  - No Content
connection: close
server: ballerina
date: Wed, 18 Jun 2025 17:03:08 +0530